# Generated by Django 4.1.7 on 2023-03-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(editable=False, null=True),
        ),
    ]
